version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: widen
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "⬆️ [Update npm]"
