version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: widen
    target-branch: "develop"
    reviewers: 
      - "miguelcolmenares"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "⬆️  [Update npm]"
