import { Acordeon } from './components/acordeon';
import { Banner } from './components/banner';
import { BlogArticle } from './components/blog-article';
import { Button } from './components/button';
import { Card } from './components/card';
import { Grid } from './components/grid';
import { Icon } from './components/icon';
import { Link } from './components/link';
import { Slider } from './components/slider';
import { TitleUnderline } from './components/title-underline';

window.customElements.define('k-acordeon', Acordeon);
window.customElements.define('k-banner', Banner);
window.customElements.define('k-blog-article', BlogArticle);
window.customElements.define('k-button', Button);
window.customElements.define('k-card', Card);
window.customElements.define('k-grid', Grid);
window.customElements.define('k-icon', Icon);
window.customElements.define('k-link', Link);
window.customElements.define('k-slider', Slider);
window.customElements.define('k-title-underline', TitleUnderline);